name = "wishlist-modal-button2"
type = "theme_app_extension"

[[blocks]]
name = "wishlist-button"
target = "section"

[[blocks]]
name = "wishlist-modal-button"
target = "section"

[app_embed]
name = "Wishlist Modal"
target = "body"
snippet_name = "wishlist-modal"